### ISSUE TITLE
mails not send

### ISSUE THREAD

**Issue by alcoxbiz** [openware/opendax#207]
Hello !

I tried all but the exchage not send out mails.
Tried all, Sendgrid and own ail server. No matter which Barong i use, VERIFY YOUR EMAIL ADDRESS  or resend Mail not work.

Exist there any Guide for email setup ?

Twillio is working 2fa aswelll.

Regards

**Comment by Galaxy-Traveler** [comment]
open port 2525

**Comment by coincryptoexchange** [comment]
I have port 25/2525/465 opened. Configured correctly the app.yml file with the sendgrid api and user details. and still nothing is being send.

**Comment by alcoxbiz** [comment]
@behnammby 
yiu found solution for the PKey error ?

**Comment by alcoxbiz** [comment]
Ok, i put the keys from hand in config/mailer.yml
SSL error is away but now get new error
{"level":"ERROR","time":"2020-08-24 15:41:40 +0000","message":"Language EN is not supported. Skipping."}

Any hint how to solve

**Comment by alcoxbiz** [comment]
Ok, got it solved

**Comment by mehmet-biter** [comment]
> Ok, got it solved

Can you show how you did it?

**Comment by alcoxbiz** [comment]
Login into your barong docker:  docker-compose exec barong bash
Install nano and edit   config/mailer.yml
Put your keys inside which you can find under opendax config mailer.yml
Then change in the barong mailer.yml all from en: to EN:
open Port 2525

**Comment by alcoxbiz** [comment]
install nano in docker 

wget http://www.nano-editor.org/dist/v2.4/nano-2.4.2.tar.gz
tar -xzf nano-2.4.2.tar.gz
cd nano-2.4.2
./configure
make
cd
./nano-2.4.2/src/nano config/mailer.yml

**Comment by mehmet-biter** [comment]
> install nano in docker
> 
> wget http://www.nano-editor.org/dist/v2.4/nano-2.4.2.tar.gz
> tar -xzf nano-2.4.2.tar.gz
> cd nano-2.4.2
> ./configure
> make
> cd
> ./nano-2.4.2/src/nano config/mailer.yml

Thank you very much brother

**Comment by alcoxbiz** [comment]
welcome

**Comment by alcoxbiz** [comment]
somehow the mailer.yml from opendax config get not copied into the barong container

**Comment by mehmet-biter** [comment]
> somehow the mailer.yml from opendax config get not copied into the barong container

yes there is missing but where

**Comment by mehmet-biter** [comment]
> somehow the mailer.yml from opendax config get not copied into the barong container

If you want, we can work together we find our mistakes sooner

**Comment by alcoxbiz** [comment]
yes now prob i use opendax 2.5

**Comment by alcoxbiz** [comment]
i close topic now as it is solved

**Comment by mehmet-biter** [comment]
> i close topic now as it is solved

ok

**Comment by phuong17889** [comment]
I have same error, and I have tested many version of barong, and here is my fix:    
add `mailer: quay.io/openware/barong:2.4.1` in `config/app.yml`
```
images:
  mailer: quay.io/openware/barong:2.4.1 #mailer worked on version 2.4.1, add this line after barong image
```
in `templates/compose/daemons.yaml.erb` change 
```
    image: "<%= @config['images']['barong'] %>"
```
to
```
    image: "<%= @config['images']['mailer'] %>"
```

**Comment by behnammby** [comment]
There are a few problems cause mailer not working and I solved. Many problems of email sending could be solved by modifying this file:
https://github.com/openware/barong/blob/master/config/initializers/barong.rb

take a look at SMPT Configuration in this file and modify your barong.rb of your own version accordingly.

1- Logo url: In new version of barong (2.5 and later), this problem is solved. They specify logo url in opendax/config/app.yml and then in email templates they use it. We can consider using this approach to solve logo problem. 
set the default logo url in barong.rb:
`  config.set(:smtp_logo_link, 'https://storage.cloud.google.com/public_peatio/logo.png')`

2- If you are using third party email servers, there is a problem with SSL verification. in barong.rb you can config ActionMailer as follows if this error is the case:
```
ActionMailer::Base.smtp_settings = {
  address: Barong::App.config.smtp_host,
  port: Barong::App.config.smtp_port,
  user_name: Barong::App.config.smtp_user,
  password: Barong::App.config.smtp_password,
  **openssl_verify_mode: OpenSSL::SSL::VERIFY_NONE**
}
```
3- if there is an error saying Language EN is not supported using the @alcoxbiz  approach will resolve the issue as I've used this approach and got it work too:
@alcoxbiz  says:
> change in the barong mailer.yml all from en: to EN:
